### ISSUE TITLE
Reset Button

### ISSUE THREAD

**Issue by trumanhess** [cs361w2019-osu/sprint1-group-4#24]
Have a button on the webpage that resets the game to a starting position. If the player clicks this a dialogue box should pop up that asks the player if they are sure they want this to happen.

**Comment by hoboabobo** [comment]
**Truman:** Handle the physical button, because start button becomes the reset button when the game begins
**Daniel:** Handle the popup window.

**Comment by trumanhess** [comment]
I have completed this issue.  I will be creating a pull request soon. I hope you don't mind Daniel, but I did your part as well.
