### ISSUE TITLE
Change start conditions [IMPORTANT]

### ISSUE THREAD

**Issue by trumanhess** [cs361w2019-osu/sprint1-group-4#29]
Multiple issues rely on this being completed.
Need to change how the game starts. Currently the game will start once the player has placed all their ships. This needs to be changed so that the game starts once the start button has been pushed.

**Comment by trumanhess** [comment]
I will try my hand at this one. If you want to help though be free to try yourself.

**Comment by hoboabobo** [comment]
Definitely work on this issue and the **start button** at the same time. I added the **Reset Button** to your pile as well because it is loosely tied to the **Start button**.

**Comment by manhaduy** [comment]
I think we can put them as separated for now since the function of the start button is quite complicated
