### ISSUE TITLE
Randomly Place AI ship (User Story 8)

### ISSUE THREAD

**Issue by hoboabobo** [cs361w2019-osu/sprint1-group-4#4]
Randomly arrange AI ships prior to the start of the game.
- ship placement must follow the same rules as human placement.

**Comment by hoboabobo** [comment]
Is this task still mine, or should this be assigned to Duncan?

**Comment by trumanhess** [comment]
This user story will be taken care of by user stories 2 and 10 because the AI uses the same function as the human place ship but with random values, which I have already taken care of. This issue will be closed.
